// <auto-generated />
using System;
using EF_Migracije.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_Migracije.Migrations
{
    [DbContext(typeof(BookStoreContext))]
    partial class BookStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EF_Migracije.Models.Author", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Ocjena")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("Author");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Bio = "Hrvatska književnica poznata po dječijim pričama",
                            Name = "Ivana Brlić-Mažuranić",
                            Ocjena = 4.0
                        },
                        new
                        {
                            ID = 2,
                            Bio = "Pisac",
                            Name = "Miroslav Krleža",
                            Ocjena = 2.0
                        });
                });

            modelBuilder.Entity("EF_Migracije.Models.Book", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AuthorId");

                    b.ToTable("Book");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AuthorId = 1,
                            Description = "",
                            Genre = "Bajka",
                            ReleaseDate = new DateTime(2024, 5, 15, 20, 53, 19, 238, DateTimeKind.Local).AddTicks(3984),
                            Stock = 10,
                            Title = "Šegrt Hlapić"
                        },
                        new
                        {
                            ID = 2,
                            AuthorId = 1,
                            Description = "",
                            Genre = "Bajka",
                            ReleaseDate = new DateTime(2024, 5, 15, 20, 53, 19, 238, DateTimeKind.Local).AddTicks(4028),
                            Stock = 14,
                            Title = "Šegrt Hlapić 2"
                        },
                        new
                        {
                            ID = 3,
                            AuthorId = 1,
                            Description = "",
                            Genre = "Bajka",
                            ReleaseDate = new DateTime(2024, 5, 15, 20, 53, 19, 238, DateTimeKind.Local).AddTicks(4030),
                            Stock = 26,
                            Title = "Šegrt Hlapić 3"
                        },
                        new
                        {
                            ID = 4,
                            AuthorId = 2,
                            Description = "",
                            Genre = "Drama",
                            ReleaseDate = new DateTime(2024, 5, 15, 20, 53, 19, 238, DateTimeKind.Local).AddTicks(4032),
                            Stock = 4,
                            Title = "Zlatarevo Zlato"
                        });
                });

            modelBuilder.Entity("EF_Migracije.Models.Book", b =>
                {
                    b.HasOne("EF_Migracije.Models.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });
#pragma warning restore 612, 618
        }
    }
}
